### ISSUE TITLE
Wrong error message for "is_empty" condition

### ISSUE THREAD

**Issue by wlma** [cliffparnitzky/FormDependentMandatoryField#12]
Hi Cliff,
many thanks for your work, saved me from braindeath ;-)

I would suggest to add another condition labeled "empty" or "is empty" to the dependent fields list. Error messages should be adapted accordingly (in German like "keine Werte in Feld xyz").  I my understanding, currently you could build it with "!=" as Condition and "*" as value which results in a wrong error message in the form.

Andreas

**Comment by cliffparnitzky** [comment]
I think this is more a bug when creating the error text.

I will fix the bug and additionally add some help texts to support better understanding of the rule combinations.

**Comment by wlma** [comment]
Hi Cliff,

thanks for fixing it, but it looks like there's an issue with the error message if only one depency is needed: in the form-error message is an additional "und" (didn't check in english though, might only in the language file)

![formular](https://cloud.githubusercontent.com/assets/1752193/20831622/1ed8380e-b886-11e6-81f3-fae6ab80efde.png)

**Comment by cliffparnitzky** [comment]
Hmpf, okay I will check this soon.

**Comment by cliffparnitzky** [comment]
Fixed in e3443ff1ba9f8d913f56accdd558ac85c62d2fa5
