### ISSUE TITLE
Eingabeprüfung "Numerische Zeichen" funktioniert nicht

### ISSUE THREAD

**Issue by Ynda** [cliffparnitzky/FormDependentMandatoryField#13]
Wenn ich ein bedingtes Formularfeld definiere und der Feldtyp hat die Eingabeprüfung auf "Numerische Zeichen" gesetzt, passiert nichts. Ändere ich diese Validierung auf z. Bsp. "Alphanumerische Zeichen" greift die Überprüfung sofort und es wird eine error-Box ausgegeben.
Es funktionieren grundsätzlich alle Eingabeprüfungen bis auf:
- Numerische Zeichen
- Telefonnummer
- E-Mail-Adresse
- Url-Format

**Comment by cliffparnitzky** [comment]
Puh, interessant ... kann es nachstellen ... werde es fixen.

**Comment by cliffparnitzky** [comment]
So, in der Class [`FormTextField`](https://github.com/contao/core/blob/master/system/modules/core/forms/FormTextField.php#L131) wird bei HTML5 Ausgabe für bestimmte Reguläre Ausdrücke als Typ der HTML5 Typ zurückgegeben.

Das betrifft gemäß Code die Werte `Numerische Zeichen`, `Telefonnummer`, `E-Mail-Adresse` und `URL-Format`.

Seit Version 2.0.0 dieser Erweiterung sind nur noch Felder konfigurierbar, die auch Werte übertragen können (siehe #11).

Diese Prüfung liefert nun aktuell aber kein Widget für z.B. `type` = `digit`. Das muss also gefixt werden.
