### ISSUE TITLE
Erweiterung für Contao 4 freigeben

### ISSUE THREAD

**Issue by mlwebworker** [cliffparnitzky/FormDependentMandatoryField#14]
Hallo Cliff,
habs auch im Forum schon schrieben https://community.contao.org/de/showthread.php?38786-DependentMandatoryFormField-Abh%C3%A4ngiges-Pflichtfeld&p=485427&viewfull=1#post485427
Die Erweiterung funktioniert nach meiner Einschätzung unter Contao 4.

**Comment by cliffparnitzky** [comment]
Realized with 537e01183d78bf5695062e9e1f35051d17eaa235
