### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by WebNetCrea** [cliffparnitzky/FormDependentMandatoryField#15]
Hello,

When i activate dependent mandatory form field, i have an error

Contao  4.7.6

Argument 1 passed to FormDependentMandatoryField::getAllInputFormFields() must be an instance of MultiColumnWizard, instance of MenAtWork\MultiColumnWizardBundle\Contao\Widgets\MultiColumnWizard given, called in /home/clients/f033bee5d301812b2774c8b8edd6a14f/web/v3/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php on line 1316

**Comment by cliffparnitzky** [comment]
I checked it with my Contao 4.7.6 and I got no error.

- Is the newest version of the extiension installed? 
- Is the MultiColumnWizard installed?

**Comment by WebNetCrea** [comment]
cliffparnitzky/form-dependent-mandatory-field  Version 2.1.2
menatwork/contao-multicolumnwizard-bundle Version 3.4.1

**Comment by WebNetCrea** [comment]
![Capture d’écran 2019-07-15 à 14 23 11](https://user-images.githubusercontent.com/3774879/61215851-40caf600-a70c-11e9-85a5-24e583dbdab7.png)

**Comment by cliffparnitzky** [comment]
Hmm, I have no idea. I tested with PHP 7.1, 7.2 and 7.3 ... no error. Must be a problem in your installation.

**Comment by cliffparnitzky** [comment]
Got no feedback :arrow_right: DECLINED
