### ISSUE TITLE
With numerical Validation text-field dependant-mandatory-section not shown in BE

### ISSUE THREAD

**Issue by Ernestopheles** [cliffparnitzky/FormDependentMandatoryField#17]
Textfield with numeric validation leads to hidden section of dependant-mandatory. If choosen Alphabetic validation or no validation its ok.
![Bildschirmfoto von 2020-05-14 15-20-18](https://user-images.githubusercontent.com/7561403/81939868-31039300-95f7-11ea-81ee-d464df61394a.png)
![Bildschirmfoto von 2020-05-14 15-19-57](https://user-images.githubusercontent.com/7561403/81939871-319c2980-95f7-11ea-8250-447d839fbe23.png)

**Comment by cliffparnitzky** [comment]
@Ernestopheles Thanks, I can confirm. Seems something in the pallets has been changed.
