### ISSUE TITLE
Contao 4.9 - dependent mandatory fields are ignored

### ISSUE THREAD

**Issue by mlwebworker** [cliffparnitzky/FormDependentMandatoryField#18]
Seit Contao 4.9 werden die abhängigen Pflichtfelder ignoriert. Das Formular wird also abgeschickt obwohl die abhängigen Pflichtfelder nicht ausgefüllt wurden.

**Comment by cliffparnitzky** [comment]
Kann ich in meinem System nicht nachvollziehen. In meinem System Contao 4.9.3 geht es: https://contao49x.contao.cliff-parnitzky.de/applications.html (das Feld "Name" hängt davon ab, ob in Salutation was ausgewählt ist).

**Comment by mlwebworker** [comment]
Wir hatten das Problem von einem Kunden der Contao Academy bekommen und ich hatte es kurz in einer Testinstallation getestet und hatte auch das Problem. Ich werde das nacher noch einmal kontrollieren und kann Dir dann einen Link schicken und ggf. auch einen Zugang geben.

**Comment by cliffparnitzky** [comment]
Okay. Ja, mit einem Beispiel können wir das besser analysieren.

**Comment by mlwebworker** [comment]
Ich habe Dir einen Link per Slack geschickt.

**Comment by mlwebworker** [comment]
Der Fehler wurde gefunden. In den Bedingungen für das Pflichtfeld war inzwischen ein falsches Bezugsfeld mit falschem Wert. Wann und wodurch das gleich bei mehreren Feldern zustande kam, konnte leider nicht mehr nachvollzogen werdn. Auf jeden Fall kein Fehler in der Erweiterung.
