### ISSUE TITLE
Dependent mandatory form Radio-button not working

### ISSUE THREAD

**Issue by Cleanerrr** [cliffparnitzky/FormDependentMandatoryField#23]
Hi,
I tried to make a Radio button dependent mandatory. That means, when a user checks first Radio(also dependent mandatory) button, then another/second Radio button should be dependent mandatory. 
This combination for me not working. 
Is it a bug, or...

**Comment by cliffparnitzky** [comment]
Hi, i have created this example and it works for me:

1. form field
![image](https://user-images.githubusercontent.com/1247552/96977267-2261c600-151d-11eb-83d7-5f8631a986d2.png)

2. form field (dependent)
![image](https://user-images.githubusercontent.com/1247552/96977343-3e656780-151d-11eb-95ed-f83886dc3cab.png)

result
![image](https://user-images.githubusercontent.com/1247552/96977380-4de4b080-151d-11eb-9aad-ba637f428b16.png)
