### ISSUE TITLE
Dependent mandatory fields are no longer queried

### ISSUE THREAD

**Issue by mlwebworker** [cliffparnitzky/FormDependentMandatoryField#24]
Nach dem Update auf **Contao 4.9.12** mit Update auf die aktuellste Version der Erweiterung ist aufgefallen, dass Formulare auch ohne das Ausfüllen der abhängigen Pflichtfelder versendet werden.
Contao: 4.9.12
PHP-ClI: 7.4.15
FormDependentManatoryField: 2.2.0

Bei einer noch installierten Testversion auf dem gleichen Server mit **Contao 4.9.8** funktioniert das noch wie es soll. Der Fehler muss irgendwann zwischen Version 4.9.8 und 4.9.12 bzw. zwischen Version 2.1.3 und 2.2.0 der Erweiterung aufgetreten sein. Beim Update von Contao wurden grundsätzlich aller installierten Erweiterungen mit upgedatet.
Contao: 4.9.8
PHP-ClI: 7.4.15
FormDependentManatoryField: 2.1.3

Nach welchem Update genau erstmalig der Fehler auftrat ist nicht bekannt, da dieser nicht sofort aufgefallen sein muss.
Ein Composer Update in der Systemwartung nach Umstellung auf Composer 2 (Contao Manager 1.4) wurde durchgeführt. Browser-Cache, Symfony-Cache und Contao-Cache wurden explizit noch einmal gelöscht.

**Comment by cliffparnitzky** [comment]
Ja, kann ich bestätigen. Hab mit Contao 4.9.12 und FormDependentMandatoryField 2.2.0 das gleiche Problem.

Muss ich untersuchen.

**Comment by mlwebworker** [comment]
Super, danke schon mal für die Info.

**Comment by cliffparnitzky** [comment]
So, ich hab mal bissel hin und her installiert: Contao 4.9.12 und FormDependentMandatoryField 2.1.3 funktioniert noch zusammen.

D.h. der Fehler liegt in der Erweiterung.

**Comment by mlwebworker** [comment]
Super schon mal. Wenn die Kundin drängelt gehe ich erst mal zurück auf 2.1.3, wenn nicht warte ich bis Du den Fehler gefunden hast.

**Comment by cliffparnitzky** [comment]
Published with https://github.com/cliffparnitzky/FormDependentMandatoryField/releases/tag/2.2.1

**Comment by cliffparnitzky** [comment]
Vielen Dank an @mlwebworker

**Comment by mlwebworker** [comment]
Danke fürs schnelle fixen.
Läuft alles wieder.
