### ISSUE TITLE
Check fails if text field is marked as phone number or e-mail address

### ISSUE THREAD

**Issue by hella-schu** [cliffparnitzky/FormDependentMandatoryField#26]
Contao 4.9.27 / FormDependentMandatoryField 2.2.1

When a field is set as phone number or e-mail address the form can be submitted while these fields are empty. When I remove the phone or e-mail attribute from these fields, the form can't be submitted with empty fields (who are dependent mandatory fields). 

Hope you understand the problem :-)

**Comment by cliffparnitzky** [comment]
Yes. I understand and can confirm.
