### ISSUE TITLE
Overlapping Fields

### ISSUE THREAD

**Issue by Fbetz** [cliffparnitzky/FormDependentMandatoryField#9]
![dependentmandatoryfield](https://cloud.githubusercontent.com/assets/7241282/2937071/92744d78-d884-11e3-8127-e0f2f5c71304.png)
Hi,
i tried to use DepenedantMandatoryFormField Version 2.0.0 with contao 3.2.8
Other relevant extensions:
efg: 2.2.1 stable
MultiColumnWizard:	3.2.0 rc3

As you can see in my screenshot, the layout is somewhat broken :-), so the fields are not useable.
Best wishes
Friedhelm

**Comment by cliffparnitzky** [comment]
Closed with version 2.0.0
